import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, shadow } from "@/constants/theme";

export function Screen({ children, title, action, scroll = true }: PropsWithChildren<{ title?: string; action?: ReactNode; scroll?: boolean }>) { const content = <View style={styles.content}>{title && <View style={styles.heading}><Text style={styles.title}>{title}</Text>{action}</View>}{children}</View>; return <SafeAreaView style={styles.safe} edges={["top"]}>{scroll ? <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">{content}</ScrollView> : content}</SafeAreaView>; }
export function Card({ children, style }: PropsWithChildren<{ style?: ViewStyle | ViewStyle[] }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function Label({ children }: PropsWithChildren) { return <Text style={styles.label}>{children}</Text>; }
export function Money({ value, compact = false }: { value: number; compact?: boolean }) { const amount = compact && Math.abs(value) >= 100000 ? `${(value / 100000).toFixed(1)}L` : Math.round(value).toLocaleString("en-IN"); return <Text style={styles.money}>₹{amount}</Text>; }
export function Progress({ value, tone = colors.accent }: { value: number; tone?: string }) { return <View style={styles.track}><View style={[styles.fill, { width: `${Math.min(100, Math.max(0, value))}%`, backgroundColor: tone }]} /></View>; }
export function Button({ title, onPress, disabled, tone = "accent" }: { title: string; onPress: () => void; disabled?: boolean; tone?: "accent" | "ink" | "quiet" }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, tone === "ink" && styles.buttonInk, tone === "quiet" && styles.buttonQuiet, (pressed || disabled) && { opacity: 0.6 }]}><Text style={[styles.buttonText, tone === "quiet" && { color: colors.ink }]}>{title}</Text></Pressable>; }
export function Field(props: TextInputProps & { label?: string }) { return <View style={{ gap: 6 }}>{props.label && <Label>{props.label}</Label>}<TextInput placeholderTextColor={colors.muted} {...props} style={[styles.input, props.style]} /></View>; }
export function Loading({ label = "Loading…" }: { label?: string }) { return <View style={styles.center}><ActivityIndicator color={colors.accent} size="large" /><Text style={styles.muted}>{label}</Text></View>; }
export function Empty({ title, body }: { title: string; body: string }) { return <Card style={styles.center}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.muted}>{body}</Text></Card>; }
export const ui = StyleSheet.create({ row: { flexDirection: "row", alignItems: "center", gap: 10 }, between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, h1: { fontSize: 34, lineHeight: 37, fontWeight: "900", color: colors.ink, letterSpacing: -1.2 }, h2: { fontSize: 20, fontWeight: "900", color: colors.ink }, body: { fontSize: 15, color: colors.inkSoft, lineHeight: 22 }, small: { fontSize: 12, color: colors.muted, fontWeight: "600" }, gap: { gap: 14 } });
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, scroll: { paddingBottom: 40 }, content: { padding: 18, gap: 16 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 2 }, title: { fontSize: 32, fontWeight: "900", color: colors.ink, letterSpacing: -1 }, card: { borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.white, padding: 16, gap: 10, ...shadow }, label: { fontSize: 10, color: colors.ink, fontWeight: "900", letterSpacing: 1.3, textTransform: "uppercase" }, money: { fontSize: 25, fontWeight: "900", color: colors.ink, letterSpacing: -0.5 }, track: { height: 10, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.paper2 }, fill: { height: "100%" }, button: { minHeight: 48, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.accent, paddingHorizontal: 16, alignItems: "center", justifyContent: "center", ...shadow }, buttonInk: { backgroundColor: colors.ink }, buttonQuiet: { backgroundColor: colors.paper }, buttonText: { color: colors.white, fontSize: 13, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7 }, input: { minHeight: 50, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.white, color: colors.ink, paddingHorizontal: 13, fontSize: 15 }, center: { minHeight: 150, alignItems: "center", justifyContent: "center", gap: 10 }, muted: { color: colors.muted, fontWeight: "600", textAlign: "center" }, emptyTitle: { fontSize: 18, fontWeight: "900", color: colors.ink } });
