import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewProps } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, shadow } from "@/constants/theme";

export function Screen({ children, title, action, scroll = true }: PropsWithChildren<{ title?: string; action?: ReactNode; scroll?: boolean }>) {
  const content = <View style={[styles.content, !scroll && styles.contentFixed]}>{title && <View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{title}</Text>{action}</View>}{children}</View>;
  return <SafeAreaView style={styles.safe} edges={["top", "left", "right"]}>{scroll ? <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets>{content}</ScrollView> : content}</SafeAreaView>;
}
export function Card({ children, style, ...props }: PropsWithChildren<ViewProps>) { return <View {...props} style={[styles.card, style]}>{children}</View>; }
export function Label({ children }: PropsWithChildren) { return <Text style={styles.label}>{children}</Text>; }
export function Money({ value, compact = false }: { value: number; compact?: boolean }) { const amount = compact && Math.abs(value) >= 100000 ? `${(value / 100000).toFixed(1)}L` : Math.round(value).toLocaleString("en-IN"); return <Text style={styles.money}>₹{amount}</Text>; }
export function Progress({ value, tone = colors.accent, label = "Progress" }: { value: number; tone?: string; label?: string }) { const normalized = Math.min(100, Math.max(0, value)); return <View accessibilityRole="progressbar" accessibilityLabel={label} accessibilityValue={{ min: 0, max: 100, now: Math.round(normalized) }} style={styles.track}><View style={[styles.fill, { width: `${normalized}%`, backgroundColor: tone }]} /></View>; }
export function Button({ title, onPress, disabled, loading = false, tone = "accent", accessibilityHint }: { title: string; onPress: () => void; disabled?: boolean; loading?: boolean; tone?: "accent" | "ink" | "quiet"; accessibilityHint?: string }) { const unavailable = disabled || loading; return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityHint={accessibilityHint} accessibilityState={{ disabled: unavailable, busy: loading }} disabled={unavailable} onPress={onPress} style={({ pressed }) => [styles.button, tone === "ink" && styles.buttonInk, tone === "quiet" && styles.buttonQuiet, (pressed || unavailable) && styles.buttonPressed]}>{loading && <ActivityIndicator color={tone === "quiet" ? colors.ink : colors.white} size="small" />}<Text style={[styles.buttonText, tone === "quiet" && { color: colors.ink }]}>{title}</Text></Pressable>; }
export function Field(props: TextInputProps & { label?: string }) { const { label, ...inputProps } = props; return <View style={styles.field}>{label && <Label>{label}</Label>}<TextInput accessibilityLabel={props.accessibilityLabel ?? label} placeholderTextColor={colors.muted} {...inputProps} style={[styles.input, props.style]} /></View>; }
export function Loading({ label = "Loading…" }: { label?: string }) { return <SafeAreaView accessibilityLiveRegion="polite" style={styles.loadingSafe}><View style={styles.center}><ActivityIndicator color={colors.accent} size="large" /><Text style={styles.muted}>{label}</Text></View></SafeAreaView>; }
export function Empty({ title, body }: { title: string; body: string }) { return <Card style={styles.center}><Text accessibilityRole="header" style={styles.emptyTitle}>{title}</Text><Text style={styles.muted}>{body}</Text></Card>; }
export function ErrorState({ title = "Couldn’t load this", body, onRetry }: { title?: string; body?: string; onRetry: () => void }) { return <Screen><Empty title={title} body={body ?? "Check your connection and try again."} /><Button title="Try again" onPress={onRetry} /></Screen>; }
export const ui = StyleSheet.create({ row: { flexDirection: "row", alignItems: "center", gap: 10 }, between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, h1: { fontSize: 34, lineHeight: 37, fontWeight: "900", color: colors.ink, letterSpacing: -1.2 }, h2: { fontSize: 20, fontWeight: "900", color: colors.ink }, body: { fontSize: 16, color: colors.inkSoft, lineHeight: 23 }, small: { fontSize: 13, color: colors.muted, fontWeight: "600" }, gap: { gap: 14 } });
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, loadingSafe: { flex: 1, backgroundColor: colors.paper, justifyContent: "center" }, scroll: { flexGrow: 1, paddingBottom: 96 }, content: { padding: 18, gap: 16 }, contentFixed: { flex: 1 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 2 }, title: { fontSize: 32, fontWeight: "900", color: colors.ink, letterSpacing: -1 }, card: { borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.white, padding: 16, gap: 10, ...shadow }, label: { fontSize: 10, color: colors.ink, fontWeight: "900", letterSpacing: 1.3, textTransform: "uppercase" }, money: { fontSize: 25, fontWeight: "900", color: colors.ink, letterSpacing: -0.5, fontVariant: ["tabular-nums"] }, track: { height: 12, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.paper2 }, fill: { height: "100%" }, button: { minHeight: 48, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.accent, paddingHorizontal: 16, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center", ...shadow }, buttonInk: { backgroundColor: colors.ink }, buttonQuiet: { backgroundColor: colors.paper }, buttonPressed: { opacity: 0.55, transform: [{ translateX: 2 }, { translateY: 2 }] }, buttonText: { color: colors.white, fontSize: 13, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7 }, field: { gap: 6 }, input: { minHeight: 50, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.white, color: colors.ink, paddingHorizontal: 13, fontSize: 16 }, center: { minHeight: 150, alignItems: "center", justifyContent: "center", gap: 10 }, muted: { color: colors.muted, fontWeight: "600", textAlign: "center", lineHeight: 20 }, emptyTitle: { fontSize: 18, fontWeight: "900", color: colors.ink, textAlign: "center" } });
