export type LearnArticle = { id: string; title: string; subtitle: string; category: "Basics" | "Investing" | "Retirement" | "Advanced"; readMins: number; level: "Beginner" | "Intermediate" | "Advanced"; sections: Array<{ heading?: string; body: string }>; action: string };
export const LEARN_ARTICLES: LearnArticle[] = [
  { id: "budgeting-101", title: "Budgeting 101", subtitle: "The 50/30/20 rule", category: "Basics", readMins: 3, level: "Beginner", action: "Set your monthly budget in Profile.", sections: [{ body: "Budgeting is deciding where your money goes before it disappears." }, { heading: "50 / 30 / 20", body: "Try 50% for needs, 30% for wants, and 20% for savings or investments. Move savings first, then spend from what remains." }] },
  { id: "inflation", title: "Why Your Money Loses Value", subtitle: "Inflation, the silent tax", category: "Basics", readMins: 3, level: "Beginner", action: "Track spending and invest the difference.", sections: [{ body: "Prices generally rise over time, so idle cash gradually buys less." }, { heading: "The response", body: "Keep near-term money safe and liquid. For long horizons, use diversified investments with the potential to outpace inflation." }] },
  { id: "compound-interest", title: "The Magic of Compounding", subtitle: "Starting early beats starting big", category: "Basics", readMins: 4, level: "Beginner", action: "Run your numbers in the SIP calculator.", sections: [{ body: "Compounding means your returns can earn returns of their own." }, { heading: "Rule of 72", body: "Divide 72 by an expected annual return to estimate how many years money could take to double. Returns are never guaranteed." }] },
  { id: "emergency-fund", title: "Emergency Fund First", subtitle: "Build your financial shock absorber", category: "Basics", readMins: 2, level: "Beginner", action: "Create an emergency-fund goal.", sections: [{ body: "Aim for three to six months of essential expenses in a safe, accessible place." }, { heading: "Why first?", body: "A cash buffer helps you avoid expensive debt or selling investments during an emergency." }] },
  { id: "what-is-sip", title: "What is a SIP?", subtitle: "A habit that builds wealth", category: "Investing", readMins: 3, level: "Beginner", action: "Start small and automate consistently.", sections: [{ body: "A systematic investment plan invests a fixed amount in a mutual fund on a schedule." }, { heading: "Consistency", body: "Regular investing reduces the pressure to guess the perfect day to enter the market." }] },
  { id: "nifty-50", title: "What is NIFTY 50?", subtitle: "A major Indian equity benchmark", category: "Investing", readMins: 3, level: "Beginner", action: "Compare low-cost diversified index funds.", sections: [{ body: "NIFTY 50 tracks 50 large companies listed on the NSE." }, { heading: "Why it matters", body: "An index fund can provide broad exposure without choosing every company yourself." }] },
  { id: "what-is-cagr", title: "What is CAGR?", subtitle: "Compare growth across time", category: "Investing", readMins: 2, level: "Beginner", action: "Compare options by annualized return.", sections: [{ body: "CAGR is the annualized rate that would turn a starting value into an ending value over a period." }, { heading: "Formula", body: "CAGR = (final value ÷ initial value)^(1 ÷ years) − 1." }] },
  { id: "fd-vs-stocks", title: "FD vs Stocks vs Mutual Funds", subtitle: "Match the tool to the goal", category: "Investing", readMins: 4, level: "Intermediate", action: "Compare FD and SIP outcomes.", sections: [{ body: "Fixed deposits emphasize predictability; stocks carry greater company-specific risk; mutual funds can provide diversification." }, { heading: "Choose by timeline", body: "Short-term essential goals usually need stability. Long-term goals can tolerate more market movement." }] },
  { id: "what-is-fire", title: "What is FIRE?", subtitle: "Financial independence explained", category: "Retirement", readMins: 4, level: "Intermediate", action: "Estimate your own FIRE target.", sections: [{ body: "Financial independence means invested assets can support your lifestyle without mandatory work income." }, { heading: "A rough target", body: "A widely used starting estimate is 25 times annual expenses, but taxes, inflation and market conditions matter." }] },
  { id: "four-percent-rule", title: "The 4% Rule", subtitle: "A withdrawal framework", category: "Retirement", readMins: 3, level: "Intermediate", action: "Review your target with realistic assumptions.", sections: [{ body: "The rule is a planning guideline for first-year portfolio withdrawals, adjusted later for inflation." }, { heading: "Not a promise", body: "Your horizon, portfolio, fees and market sequence can change what is sustainable." }] },
  { id: "why-start-at-21", title: "Why Start Investing at 21", subtitle: "Give compounding more time", category: "Retirement", readMins: 3, level: "Beginner", action: "Automate a manageable monthly amount.", sections: [{ body: "Each earlier year adds another possible compounding cycle." }, { heading: "The habit advantage", body: "A small repeatable contribution is more useful than an ambitious plan you cannot sustain." }] },
  { id: "asset-allocation", title: "Asset Allocation", subtitle: "Divide money by risk and timeline", category: "Advanced", readMins: 4, level: "Advanced", action: "Align each goal with an appropriate risk bucket.", sections: [{ body: "Asset allocation is the mix of equity, debt, cash and other assets in a portfolio." }, { heading: "Rebalance", body: "Review periodically and restore the intended mix when market movement shifts your risk." }] },
];
export function getLearnArticleById(id: string) { return LEARN_ARTICLES.find((article) => article.id === id); }
