"use client";

import { useRef, useState, type FormEvent } from "react";
import { Bot, Send, ShieldCheck, UserRound } from "lucide-react";
import { PageHeading } from "./page-state";
import { jsonRequest } from "./use-gig-dashboard";

type Message = { id: number; role: "assistant" | "user"; text: string };
const suggestions = ["How much can I safely spend?", "What if my payout is late?", "How do I grow my cushion?", "Explain my resilience score"];

export function CoachClient() {
  const [messages, setMessages] = useState<Message[]>([{ id: 1, role: "assistant", text: "Ask me about your current plan. I use the same settled balance, commitments, work costs, and payout range shown elsewhere in SuperFinz." }]); const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const id = useRef(2);
  const ask = async (question: string) => { if (!question.trim() || busy) return; const userMessage = { id: id.current++, role: "user" as const, text: question.trim() }; setMessages((current) => [...current, userMessage]); setInput(""); setBusy(true); setError(null); try { const body = await jsonRequest<{ reply: string }>("/api/gig/coach", { method: "POST", body: JSON.stringify({ message: userMessage.text }) }); setMessages((current) => [...current, { id: id.current++, role: "assistant", text: body.reply }]); } catch (cause) { setError(cause instanceof Error ? cause.message : "The coach could not answer"); } finally { setBusy(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); void ask(input); };
  return <div className="space-y-6"><PageHeading eyebrow="Money coach" title="Ask about your real plan." copy="Short, clear answers grounded in your recorded numbers. This is planning guidance—not a loan decision or financial guarantee." />
    <div className="grid gap-5 xl:grid-cols-[1fr_18rem]"><section className="brut-card flex min-h-[36rem] flex-col overflow-hidden"><div className="flex items-center gap-3 border-b-2 border-ink bg-ink p-4 text-paper"><div className="flex h-11 w-11 items-center justify-center border-2 border-paper"><Bot aria-hidden size={21} /></div><div><p className="font-black">SuperFinz Coach</p><p className="text-xs font-semibold text-paper-2">Uses your current deterministic plan</p></div></div><div className="flex-1 space-y-4 p-4" aria-live="polite">{messages.map((message) => <article key={message.id} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>{message.role === "assistant" && <div className="flex h-10 w-10 shrink-0 items-center justify-center border-2 border-ink bg-accent-soft"><Bot aria-hidden size={18} /></div>}<div className={`max-w-[85%] border-2 border-ink p-4 text-sm font-semibold leading-6 ${message.role === "user" ? "bg-ink text-paper" : "bg-paper-2"}`}>{message.text}</div>{message.role === "user" && <div className="flex h-10 w-10 shrink-0 items-center justify-center border-2 border-ink bg-good-soft"><UserRound aria-hidden size={18} /></div>}</article>)}{busy && <div className="flex items-center gap-3" role="status"><div className="flex h-10 w-10 items-center justify-center border-2 border-ink bg-accent-soft"><Bot aria-hidden size={18} /></div><div className="border-2 border-ink bg-paper-2 p-4 text-sm font-black">Checking your plan…</div></div>}{error && <div role="alert" className="border-2 border-bad bg-bad-soft p-3 text-sm font-bold text-bad">{error} <button type="button" onClick={() => void ask(messages.at(-1)?.role === "user" ? messages.at(-1)!.text : input)} className="ml-2 underline">Retry</button></div>}</div><form onSubmit={submit} className="flex gap-2 border-t-2 border-ink bg-paper-2 p-3"><label className="sr-only" htmlFor="coach-question">Ask the money coach</label><input id="coach-question" value={input} onChange={(event) => setInput(event.target.value)} maxLength={500} placeholder="Can I afford ₹500 for repairs?" className="min-h-12 min-w-0 flex-1 border-2 border-ink bg-paper px-3 text-base font-bold outline-none focus:ring-4 focus:ring-accent/30" /><button disabled={busy || !input.trim()} aria-label="Send question" className="brut-btn min-h-12 bg-accent text-paper"><Send aria-hidden size={18} /><span className="hidden sm:inline">Send</span></button></form></section>
      <aside className="space-y-4"><section className="brut-card p-5"><p className="brut-label">Try asking</p><div className="mt-3 space-y-2">{suggestions.map((suggestion) => <button key={suggestion} type="button" disabled={busy} onClick={() => void ask(suggestion)} className="min-h-12 w-full border-2 border-ink bg-paper px-3 text-left text-xs font-black hover:bg-accent-soft focus:outline-2 focus:outline-offset-2 focus:outline-ink">{suggestion}</button>)}</div></section><section className="brut-card bg-good-soft p-5"><ShieldCheck aria-hidden size={23} /><p className="brut-label mt-4">Honest by design</p><p className="mt-3 text-sm font-semibold leading-6">Known numbers and estimates are labeled separately. The coach cannot approve credit, move money, or invent a balance.</p></section></aside></div>
  </div>;
}
