"use client";

import { useState, type FormEvent } from "react";
import { ArrowDownLeft, ArrowUpRight, CirclePlus, Scissors, Trash2, WalletCards, X } from "lucide-react";
import type { CashEntryKind } from "@superfinz/shared";
import { formatCurrency, formatDate } from "@/lib/utils";
import { ErrorPanel, LoadingPanel, PageHeading } from "./page-state";
import { jsonRequest, useGigDashboard } from "./use-gig-dashboard";

const today = () => new Date().toISOString().slice(0, 10);
const kindLabels: Record<CashEntryKind, string> = { INCOME: "Other income", WORK_EXPENSE: "Work expense", ESSENTIAL_EXPENSE: "Essential expense", FLEXIBLE_EXPENSE: "Flexible expense", COMMITMENT_PAYMENT: "Commitment payment", POCKET_ALLOCATION: "Pocket allocation", TRANSFER: "Transfer" };

export function IncomeClient() {
  const { dashboard, loading, error, refresh } = useGigDashboard();
  const [mode, setMode] = useState<"entry" | "payout" | null>(null);
  const [entry, setEntry] = useState({ kind: "WORK_EXPENSE" as CashEntryKind, amount: "", category: "Fuel", note: "", date: today() });
  const [payout, setPayout] = useState({ sourceId: "", amount: "", date: today(), note: "" });
  const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState<string | null>(null);

  if (loading) return <LoadingPanel label="Loading income" />;
  if (error || !dashboard) return <ErrorPanel message={error ?? "No plan found"} retry={refresh} />;
  const rule = dashboard.splitRule; const activeSources = dashboard.sources.filter((source) => source.status === "ACTIVE"); const selectedSource = activeSources.find((source) => source.id === payout.sourceId) ?? activeSources[0]; const payoutAmount = Number(payout.amount) || 0;
  const splitRows = [["Essentials", rule.essentialsPct], ["Work costs", rule.workCostsPct], ["Cushion", rule.emergencyPct], ["Long-term", rule.longTermPct], ["Flexible", rule.flexiblePct]] as const;

  const submitEntry = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setActionError(null); try { await jsonRequest("/api/gig/entries", { method: "POST", body: JSON.stringify({ kind: entry.kind, amount: Number(entry.amount), category: entry.category.trim(), paymentMethod: "MANUAL", note: entry.note.trim() || null, workRelated: entry.kind === "WORK_EXPENSE", status: entry.kind === "INCOME" ? "SETTLED" : "PAID", date: new Date(`${entry.date}T12:00:00`).toISOString() }) }); setEntry({ kind: "WORK_EXPENSE", amount: "", category: "Fuel", note: "", date: today() }); setMode(null); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not save entry"); } finally { setBusy(false); } };
  const submitPayout = async (event: FormEvent) => { event.preventDefault(); if (!selectedSource) return; setBusy(true); setActionError(null); try { await jsonRequest("/api/gig/split", { method: "POST", body: JSON.stringify({ sourceId: selectedSource.id, sourceName: selectedSource.name, amount: payoutAmount, receivedAt: new Date(`${payout.date}T12:00:00`).toISOString(), note: payout.note.trim() || null, percentages: { essentialsPct: rule.essentialsPct, workCostsPct: rule.workCostsPct, emergencyPct: rule.emergencyPct, longTermPct: rule.longTermPct, flexiblePct: rule.flexiblePct } }) }); setPayout({ sourceId: "", amount: "", date: today(), note: "" }); setMode(null); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not split payout"); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (dashboard.entries.find((item) => item.id === id)?.payoutSplitId) { setActionError("A Smart Split payout is protected because deleting it would also change all five pockets."); return; } setBusy(true); setActionError(null); try { await jsonRequest(`/api/gig/entries/${id}`, { method: "DELETE" }); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not delete entry"); } finally { setBusy(false); } };

  return <div className="space-y-6"><PageHeading eyebrow="Cashbook" title="Income & costs." copy="Record settled money, protect the costs of earning, and split each payout with one clear rule." action={<div className="flex flex-wrap gap-2"><button type="button" onClick={() => setMode(mode === "entry" ? null : "entry")} className="brut-btn min-h-12 bg-paper"><CirclePlus aria-hidden size={17} />Add entry</button><button type="button" onClick={() => setMode(mode === "payout" ? null : "payout")} className="brut-btn min-h-12 bg-accent text-paper"><Scissors aria-hidden size={17} />Record payout</button></div>} />
    <section className="grid gap-4 sm:grid-cols-3" aria-label="Income summary"><Stat label="This week's gross" value={formatCurrency(dashboard.summary.grossIncomeWeek)} /><Stat label="Work costs" value={formatCurrency(dashboard.summary.workCostsWeek)} tone="warn" /><Stat label="True take-home" value={formatCurrency(dashboard.summary.trueNetIncomeWeek)} tone="good" /></section>
    {mode === "entry" && <section className="brut-card-lg p-5 sm:p-6"><div className="flex justify-between"><div><p className="brut-label">New cashbook entry</p><h2 className="brut-display mt-1 text-3xl">What changed?</h2></div><button type="button" aria-label="Close form" onClick={() => setMode(null)} className="flex h-11 w-11 items-center justify-center border-2 border-ink"><X aria-hidden size={19} /></button></div><form onSubmit={submitEntry} className="mt-6 grid gap-4 sm:grid-cols-2"><SelectField label="Entry type" value={entry.kind} onChange={(value) => setEntry((current) => ({ ...current, kind: value as CashEntryKind }))}>{(["INCOME", "WORK_EXPENSE", "ESSENTIAL_EXPENSE", "FLEXIBLE_EXPENSE"] as CashEntryKind[]).map((kind) => <option key={kind} value={kind}>{kindLabels[kind]}</option>)}</SelectField><Field label="Amount" type="number" value={entry.amount} onChange={(value) => setEntry((current) => ({ ...current, amount: value }))} /><Field label="Category" value={entry.category} onChange={(value) => setEntry((current) => ({ ...current, category: value }))} /><Field label="Date" type="date" value={entry.date} onChange={(value) => setEntry((current) => ({ ...current, date: value }))} /><Field label="Note (optional)" value={entry.note} onChange={(value) => setEntry((current) => ({ ...current, note: value }))} className="sm:col-span-2" />{actionError && <ActionError message={actionError} />}<button disabled={busy || Number(entry.amount) <= 0 || !entry.category.trim()} className="brut-btn min-h-12 bg-ink text-paper sm:col-span-2">{busy ? "Saving…" : "Save settled entry"}</button></form></section>}
    {mode === "payout" && <section className="brut-card-lg bg-accent-soft p-5 sm:p-6"><div className="flex justify-between"><div><p className="brut-label">Smart Split</p><h2 className="brut-display mt-1 text-3xl">Record a settled payout.</h2><p className="mt-2 text-sm font-semibold text-ink-soft">This updates the cashbook and all five pockets together.</p></div><button type="button" aria-label="Close form" onClick={() => setMode(null)} className="flex h-11 w-11 items-center justify-center border-2 border-ink bg-paper"><X aria-hidden size={19} /></button></div><form onSubmit={submitPayout} className="mt-6 grid gap-4 sm:grid-cols-2"><SelectField label="Income source" value={selectedSource?.id ?? ""} onChange={(value) => setPayout((current) => ({ ...current, sourceId: value }))}>{activeSources.map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</SelectField><Field label="Payout amount" type="number" value={payout.amount} onChange={(value) => setPayout((current) => ({ ...current, amount: value }))} /><Field label="Received date" type="date" value={payout.date} onChange={(value) => setPayout((current) => ({ ...current, date: value }))} /><Field label="Note (optional)" value={payout.note} onChange={(value) => setPayout((current) => ({ ...current, note: value }))} /><div className="border-2 border-ink bg-paper p-4 sm:col-span-2"><p className="brut-label">Review before confirming</p><div className="mt-3 grid gap-2 sm:grid-cols-5">{splitRows.map(([label, percentage]) => <div key={label}><p className="text-xs font-bold text-ink-soft">{label} · {percentage}%</p><p className="num text-lg font-black">{formatCurrency(payoutAmount * percentage / 100)}</p></div>)}</div><p className="mt-4 border-t-2 border-ink pt-3 text-xs font-bold">Prototype: this records a plan inside SuperFinz. It does not move money at a bank.</p></div>{actionError && <ActionError message={actionError} />}<button disabled={busy || payoutAmount <= 0 || !selectedSource} className="brut-btn min-h-12 bg-ink text-paper sm:col-span-2">{busy ? "Applying…" : "Confirm payout and split"}</button></form></section>}
    {!mode && actionError && <ActionError message={actionError} />}
    <div className="grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><section className="brut-card overflow-hidden"><div className="flex items-center justify-between border-b-2 border-ink bg-paper-2 p-4"><div><p className="brut-label">Cashbook</p><h2 className="mt-1 text-xl font-black">Settled activity</h2></div><span className="brut-stamp">{dashboard.entries.length} entries</span></div>{dashboard.entries.length === 0 ? <Empty copy="Add the first settled income or cost." /> : <div>{dashboard.entries.slice(0, 25).map((item) => { const incoming = item.kind === "INCOME"; return <article key={item.id} className="flex min-h-20 items-center gap-3 border-b border-ink/30 px-4 py-3 last:border-b-0"><div className={`flex h-11 w-11 shrink-0 items-center justify-center border-2 border-ink ${incoming ? "bg-good-soft" : "bg-warn-soft"}`}>{incoming ? <ArrowDownLeft aria-hidden size={18} /> : <ArrowUpRight aria-hidden size={18} />}</div><div className="min-w-0 flex-1"><p className="truncate font-black">{item.sourceName ?? item.category}</p><p className="truncate text-xs font-semibold text-ink-soft">{kindLabels[item.kind]} · {formatDate(item.date)}{item.note ? ` · ${item.note}` : ""}</p></div><p className={`num whitespace-nowrap text-lg font-black ${incoming ? "text-good" : "text-bad"}`}>{incoming ? "+" : "−"}{formatCurrency(item.amount)}</p><button type="button" aria-label={`Delete ${item.category} entry`} onClick={() => void remove(item.id)} disabled={busy} className="flex h-11 w-11 shrink-0 items-center justify-center border-2 border-transparent text-bad hover:border-ink hover:bg-bad-soft"><Trash2 aria-hidden size={17} /></button></article>; })}</div>}</section><aside className="space-y-4"><section className="brut-card p-5"><WalletCards aria-hidden size={23} /><p className="brut-label mt-4">Income sources</p><div className="mt-3 space-y-3">{dashboard.sources.map((source) => <div key={source.id} className="border-t-2 border-ink pt-3 first:border-0 first:pt-0"><div className="flex justify-between gap-2"><strong>{source.name}</strong><span className={`brut-stamp ${source.status === "ACTIVE" ? "bg-good-soft" : "bg-paper-2"}`}>{source.status}</span></div><p className="mt-1 text-xs font-semibold text-ink-soft">{formatCurrency(source.typicalMin)}–{formatCurrency(source.typicalMax)} · {source.frequency.toLowerCase()}</p></div>)}</div></section><section className="border-2 border-ink bg-ink p-5 text-paper"><p className="brut-label !text-paper-2">Known vs expected</p><p className="mt-3 text-sm font-semibold leading-6">Only settled cash changes your available balance. Expected payouts stay estimates until you confirm receipt.</p></section></aside></div>
  </div>;
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: "warn" | "good" }) { return <div className={`brut-card p-5 ${tone === "warn" ? "bg-warn-soft" : tone === "good" ? "bg-good-soft" : ""}`}><p className="brut-label">{label}</p><p className="num mt-2 text-3xl font-black">{value}</p></div>; }
function Field({ label, value, onChange, type = "text", className = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; className?: string }) { return <label className={`grid gap-2 ${className}`}><span className="brut-label">{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 border-2 border-ink bg-paper px-3 text-base font-bold outline-none focus:ring-4 focus:ring-accent/30" required={label !== "Note (optional)"} /></label>; }
function SelectField({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="grid gap-2"><span className="brut-label">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 border-2 border-ink bg-paper px-3 text-base font-bold outline-none focus:ring-4 focus:ring-accent/30">{children}</select></label>; }
function ActionError({ message }: { message: string }) { return <p role="alert" className="border-2 border-bad bg-bad-soft p-3 text-sm font-bold text-bad sm:col-span-2">{message}</p>; }
function Empty({ copy }: { copy: string }) { return <div className="p-10 text-center"><p className="brut-display text-2xl">Nothing recorded yet.</p><p className="mt-2 text-sm font-semibold text-ink-soft">{copy}</p></div>; }
