"use client";

import { useMemo, useState, type FormEvent } from "react";
import { CalendarCheck, CirclePlus, Clock3, Gauge, Target, Trash2 } from "lucide-react";
import { formatCurrency, formatDate } from "@/lib/utils";
import { ErrorPanel, LoadingPanel, PageHeading } from "./page-state";
import { jsonRequest, useGigDashboard } from "./use-gig-dashboard";

const futureDate = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);

export function PlanClient() {
  const { dashboard, loading, error, refresh } = useGigDashboard();
  const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState<string | null>(null);
  const [form, setForm] = useState({ title: "", amount: "", dueDate: futureDate(7), recurrence: "MONTHLY" });
  const [scenario, setScenario] = useState({ incomeChange: 0, payoutDelay: 0, surpriseCost: 0 });

  const scenarioResult = useMemo(() => { if (!dashboard) return null; const baseline = dashboard.summary.forecastIncomeLow30d - dashboard.summary.committedOutflow30d - dashboard.summary.estimatedWorkCosts30d; const adjustedIncome = dashboard.summary.forecastIncomeLow30d * (1 + scenario.incomeChange / 100); const delayCost = dashboard.profile.weeklyWorkCosts / 7 * scenario.payoutDelay; const end = adjustedIncome - dashboard.summary.committedOutflow30d - dashboard.summary.estimatedWorkCosts30d - delayCost - scenario.surpriseCost; return { baseline, end, change: end - baseline }; }, [dashboard, scenario]);
  if (loading) return <LoadingPanel label="Building your 30-day plan" />;
  if (error || !dashboard || !scenarioResult) return <ErrorPanel message={error ?? "No plan found"} retry={refresh} />;

  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setActionError(null); try { await jsonRequest("/api/gig/commitments", { method: "POST", body: JSON.stringify({ title: form.title.trim(), category: form.title.trim(), amount: Number(form.amount), dueDate: new Date(`${form.dueDate}T12:00:00`).toISOString(), recurrence: form.recurrence, essential: true, priority: 1, autopay: false }) }); setForm({ title: "", amount: "", dueDate: futureDate(7), recurrence: "MONTHLY" }); setShowForm(false); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not add commitment"); } finally { setBusy(false); } };
  const markPaid = async (id: string) => { setBusy(true); setActionError(null); try { await jsonRequest("/api/gig/commitments", { method: "PATCH", body: JSON.stringify({ id, status: "PAID" }) }); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not mark this paid"); } finally { setBusy(false); } };
  const remove = async (id: string) => { setBusy(true); setActionError(null); try { await jsonRequest("/api/gig/commitments", { method: "DELETE", body: JSON.stringify({ id }) }); await refresh(); } catch (cause) { setActionError(cause instanceof Error ? cause.message : "Could not remove commitment"); } finally { setBusy(false); } };

  const lowNet = dashboard.summary.forecastIncomeLow30d - dashboard.summary.committedOutflow30d - dashboard.summary.estimatedWorkCosts30d; const highNet = dashboard.summary.forecastIncomeHigh30d - dashboard.summary.committedOutflow30d - dashboard.summary.estimatedWorkCosts30d; const earningGap = Math.max(0, dashboard.summary.committedOutflow30d + dashboard.summary.estimatedWorkCosts30d + dashboard.profile.safetyBuffer - dashboard.summary.forecastIncomeLow30d);
  return <div className="space-y-6"><PageHeading eyebrow="30-day planner" title="Plan the uneven month." copy="Use a range, not one optimistic forecast. Expected earnings stay separate from money already received." action={<button type="button" onClick={() => setShowForm((value) => !value)} className="brut-btn min-h-12 bg-accent text-paper"><CirclePlus aria-hidden size={17} />Add commitment</button>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Forecast label="Income range" value={`${formatCurrency(dashboard.summary.forecastIncomeLow30d)}–${formatCurrency(dashboard.summary.forecastIncomeHigh30d)}`} detail={`${dashboard.summary.forecastConfidence.toLowerCase()} confidence`} /><Forecast label="Commitments" value={formatCurrency(dashboard.summary.committedOutflow30d)} detail="Next 30 days" /><Forecast label="Work costs" value={formatCurrency(dashboard.summary.estimatedWorkCosts30d)} detail="Estimated from your pattern" /><Forecast label="End-of-month range" value={`${formatCurrency(lowNet)}–${formatCurrency(highNet)}`} detail="Before flexible spending" tone={lowNet < 0 ? "bad" : "good"} /></section>
    {showForm && <section className="brut-card-lg p-5 sm:p-6"><p className="brut-label">New commitment</p><h2 className="brut-display mt-1 text-3xl">Protect a due payment.</h2><form onSubmit={create} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Name" value={form.title} onChange={(value) => setForm((current) => ({ ...current, title: value }))} /><Field label="Amount" type="number" value={form.amount} onChange={(value) => setForm((current) => ({ ...current, amount: value }))} /><Field label="Due date" type="date" value={form.dueDate} onChange={(value) => setForm((current) => ({ ...current, dueDate: value }))} /><label className="grid gap-2"><span className="brut-label">Repeats</span><select value={form.recurrence} onChange={(event) => setForm((current) => ({ ...current, recurrence: event.target.value }))} className="min-h-12 border-2 border-ink bg-paper px-3 text-base font-bold"><option value="WEEKLY">Weekly</option><option value="FORTNIGHTLY">Fortnightly</option><option value="MONTHLY">Monthly</option><option value="ONE_TIME">One time</option></select></label>{actionError && <ActionError message={actionError} />}<div className="flex gap-3 sm:col-span-2"><button type="button" onClick={() => setShowForm(false)} className="brut-btn min-h-12 flex-1 bg-paper">Cancel</button><button disabled={busy || !form.title.trim() || Number(form.amount) <= 0} className="brut-btn min-h-12 flex-1 bg-ink text-paper">{busy ? "Saving…" : "Add commitment"}</button></div></form></section>}
    {!showForm && actionError && <ActionError message={actionError} />}
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="brut-card overflow-hidden"><div className="border-b-2 border-ink bg-paper-2 p-4"><p className="brut-label">Payment calendar</p><h2 className="mt-1 text-xl font-black">Upcoming commitments</h2></div>{dashboard.commitments.length === 0 ? <div className="p-10 text-center font-semibold text-ink-soft">No commitments yet.</div> : dashboard.commitments.map((item) => <article key={item.id} className="flex flex-wrap items-center gap-3 border-b border-ink/30 p-4 last:border-b-0"><div className={`flex h-11 w-11 shrink-0 items-center justify-center border-2 border-ink ${item.status === "PAID" ? "bg-good-soft" : "bg-warn-soft"}`}><CalendarCheck aria-hidden size={18} /></div><div className="min-w-40 flex-1"><p className="font-black">{item.title}</p><p className="text-xs font-semibold text-ink-soft">Due {formatDate(item.dueDate)} · {item.recurrence.toLowerCase().replace("_", " ")}</p></div><div className="text-right"><p className="num text-lg font-black">{formatCurrency(item.amount)}</p><span className={`text-[10px] font-black uppercase ${item.status === "PAID" ? "text-good" : "text-warn"}`}>{item.status}</span></div>{item.status !== "PAID" && <button type="button" disabled={busy} onClick={() => void markPaid(item.id)} className="min-h-11 border-2 border-ink bg-good-soft px-3 text-xs font-black uppercase">Mark paid</button>}<button type="button" disabled={busy} onClick={() => void remove(item.id)} aria-label={`Delete ${item.title}`} className="flex h-11 w-11 items-center justify-center border-2 border-transparent text-bad hover:border-ink hover:bg-bad-soft"><Trash2 aria-hidden size={17} /></button></article>)}</section>
      <aside className="space-y-4"><section className={`brut-card p-5 ${earningGap > 0 ? "bg-warn-soft" : "bg-good-soft"}`}><Target aria-hidden size={23} /><p className="brut-label mt-4">Minimum earning target</p><p className="num mt-2 text-4xl font-black">{formatCurrency(earningGap)}</p><p className="mt-2 text-sm font-semibold leading-6">{earningGap > 0 ? "Extra settled income needed in the low case to cover commitments, work costs, and your buffer." : "Your low-case forecast covers the current protected plan."}</p></section><section className="brut-card p-5"><Clock3 aria-hidden size={23} /><p className="brut-label mt-4">Next known events</p><div className="mt-3 space-y-3">{dashboard.timeline.slice(0, 4).map((event) => <div key={event.id} className="border-t-2 border-ink pt-3 first:border-0 first:pt-0"><div className="flex justify-between gap-3"><strong className="text-sm">{event.title}</strong><span className="num whitespace-nowrap text-sm font-black">{event.amountMin === event.amountMax ? formatCurrency(event.amountMin) : `${formatCurrency(event.amountMin)}–${formatCurrency(event.amountMax)}`}</span></div><p className="mt-1 text-xs font-semibold text-ink-soft">{formatDate(event.date)} · {event.status.toLowerCase()}</p></div>)}</div></section></aside></div>
    <section className="brut-card-lg bg-ink p-5 text-paper sm:p-6"><div className="flex items-start gap-3"><Gauge aria-hidden className="text-accent" size={25} /><div><p className="brut-label !text-paper-2">Scenario tester</p><h2 className="brut-display mt-1 text-3xl">What if the month changes?</h2><p className="mt-2 text-sm font-semibold text-paper-2">This is a private planning calculation. It does not change your saved data.</p></div></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><Range label="Income change" min={-50} max={30} step={5} value={scenario.incomeChange} suffix="%" onChange={(value) => setScenario((current) => ({ ...current, incomeChange: value }))} /><Range label="Payout delay" min={0} max={14} step={1} value={scenario.payoutDelay} suffix=" days" onChange={(value) => setScenario((current) => ({ ...current, payoutDelay: value }))} /><Range label="Surprise cost" min={0} max={10000} step={250} value={scenario.surpriseCost} prefix="₹" onChange={(value) => setScenario((current) => ({ ...current, surpriseCost: value }))} /></div><div className="mt-6 grid gap-3 border-2 border-paper-2 p-4 sm:grid-cols-3"><ForecastDark label="Low-case baseline" value={formatCurrency(scenarioResult.baseline)} /><ForecastDark label="Scenario result" value={formatCurrency(scenarioResult.end)} /><ForecastDark label="Difference" value={`${scenarioResult.change >= 0 ? "+" : ""}${formatCurrency(scenarioResult.change)}`} /></div></section>
  </div>;
}

function Forecast({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: "bad" | "good" }) { return <div className={`brut-card p-5 ${tone === "bad" ? "bg-bad-soft" : tone === "good" ? "bg-good-soft" : ""}`}><p className="brut-label">{label}</p><p className="num mt-2 text-2xl font-black">{value}</p><p className="mt-2 text-xs font-semibold text-ink-soft">{detail}</p></div>; }
function ForecastDark({ label, value }: { label: string; value: string }) { return <div><p className="brut-label !text-paper-2">{label}</p><p className="num mt-1 text-2xl font-black">{value}</p></div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2"><span className="brut-label">{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 border-2 border-ink bg-paper px-3 text-base font-bold outline-none focus:ring-4 focus:ring-accent/30" required /></label>; }
function ActionError({ message }: { message: string }) { return <p role="alert" className="border-2 border-bad bg-bad-soft p-3 text-sm font-bold text-bad sm:col-span-2">{message}</p>; }
function Range({ label, value, min, max, step, onChange, prefix = "", suffix = "" }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void; prefix?: string; suffix?: string }) { return <label className="grid gap-2"><span className="flex justify-between text-xs font-black uppercase tracking-wide"><span>{label}</span><strong className="num text-accent">{prefix}{value.toLocaleString("en-IN")}{suffix}</strong></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="h-11 w-full accent-accent" /></label>; }
