"use client";

import { useEffect, useState, type FormEvent } from "react";
import { signOut } from "next-auth/react";
import { Database, LogOut, Pause, Play, Save, Unplug } from "lucide-react";
import { ErrorPanel, LoadingPanel, PageHeading } from "./page-state";
import { jsonRequest, useGigDashboard } from "./use-gig-dashboard";

type SettingsForm = { preferredName: string; city: string; preferredLanguage: string; safetyBuffer: string; cushionTargetDays: string; essentialsPct: string; workCostsPct: string; emergencyPct: string; longTermPct: string; flexiblePct: string; enabled: boolean };
const empty: SettingsForm = { preferredName: "", city: "", preferredLanguage: "English", safetyBuffer: "0", cushionTargetDays: "30", essentialsPct: "55", workCostsPct: "15", emergencyPct: "10", longTermPct: "5", flexiblePct: "15", enabled: true };

export function SettingsClient() {
  const { dashboard, loading, error, refresh } = useGigDashboard(); const [form, setForm] = useState(empty); const [hydratedId, setHydratedId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ tone: "good" | "bad"; text: string } | null>(null);
  useEffect(() => { if (!dashboard || hydratedId === dashboard.profile.id) return; setForm({ preferredName: dashboard.profile.preferredName, city: dashboard.profile.city, preferredLanguage: dashboard.profile.preferredLanguage, safetyBuffer: String(dashboard.profile.safetyBuffer), cushionTargetDays: String(dashboard.profile.cushionTargetDays), essentialsPct: String(dashboard.splitRule.essentialsPct), workCostsPct: String(dashboard.splitRule.workCostsPct), emergencyPct: String(dashboard.splitRule.emergencyPct), longTermPct: String(dashboard.splitRule.longTermPct), flexiblePct: String(dashboard.splitRule.flexiblePct), enabled: dashboard.splitRule.enabled }); setHydratedId(dashboard.profile.id); }, [dashboard, hydratedId]);
  if (loading) return <LoadingPanel label="Loading settings" />;
  if (error || !dashboard) return <ErrorPanel message={error ?? "No plan found"} retry={refresh} />;
  const splitTotal = Number(form.essentialsPct) + Number(form.workCostsPct) + Number(form.emergencyPct) + Number(form.longTermPct) + Number(form.flexiblePct); const set = (key: keyof SettingsForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { await jsonRequest("/api/gig/settings", { method: "PATCH", body: JSON.stringify({ preferredName: form.preferredName.trim(), city: form.city.trim(), preferredLanguage: form.preferredLanguage.trim(), safetyBuffer: Number(form.safetyBuffer), cushionTargetDays: Number(form.cushionTargetDays), splitRule: { essentialsPct: Number(form.essentialsPct), workCostsPct: Number(form.workCostsPct), emergencyPct: Number(form.emergencyPct), longTermPct: Number(form.longTermPct), flexiblePct: Number(form.flexiblePct), enabled: form.enabled } }) }); setMessage({ tone: "good", text: "Settings saved." }); setHydratedId(null); await refresh(); } catch (cause) { setMessage({ tone: "bad", text: cause instanceof Error ? cause.message : "Could not save settings" }); } finally { setBusy(false); } };
  const sourceStatus = async (id: string, status: "ACTIVE" | "PAUSED" | "REVOKED") => { setBusy(true); setMessage(null); try { await jsonRequest("/api/gig/sources", { method: "PATCH", body: JSON.stringify({ id, status }) }); setMessage({ tone: "good", text: `Income source ${status.toLowerCase()}.` }); await refresh(); } catch (cause) { setMessage({ tone: "bad", text: cause instanceof Error ? cause.message : "Could not update source" }); } finally { setBusy(false); } };
  return <div className="space-y-6"><PageHeading eyebrow="Settings & consent" title="Keep the plan yours." copy="Update the protection rule, control every data source, and see exactly which connections are simulated." />
    <form onSubmit={save} className="grid gap-5 xl:grid-cols-2"><section className="brut-card p-5 sm:p-6"><p className="brut-label">Worker profile</p><h2 className="brut-display mt-1 text-3xl">Your planning basics.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Preferred name" value={form.preferredName} onChange={(value) => set("preferredName", value)} /><Field label="City" value={form.city} onChange={(value) => set("city", value)} /><Field label="Preferred language" value={form.preferredLanguage} onChange={(value) => set("preferredLanguage", value)} /><Field label="Minimum safety buffer" type="number" value={form.safetyBuffer} onChange={(value) => set("safetyBuffer", value)} /><Field label="Cushion goal (days)" type="number" value={form.cushionTargetDays} onChange={(value) => set("cushionTargetDays", value)} /></div></section>
      <section className="brut-card bg-accent-soft p-5 sm:p-6"><p className="brut-label">Smart Split rule</p><h2 className="brut-display mt-1 text-3xl">Every payout gets a job.</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Essentials (%)" type="number" value={form.essentialsPct} onChange={(value) => set("essentialsPct", value)} /><Field label="Work costs (%)" type="number" value={form.workCostsPct} onChange={(value) => set("workCostsPct", value)} /><Field label="Emergency cushion (%)" type="number" value={form.emergencyPct} onChange={(value) => set("emergencyPct", value)} /><Field label="Long-term savings (%)" type="number" value={form.longTermPct} onChange={(value) => set("longTermPct", value)} /><Field label="Flexible spending (%)" type="number" value={form.flexiblePct} onChange={(value) => set("flexiblePct", value)} /><div className="flex min-h-12 items-center justify-between border-2 border-ink bg-paper px-3"><span className="brut-label">Total</span><strong className={`num text-xl ${splitTotal === 100 ? "text-good" : "text-bad"}`}>{splitTotal}%</strong></div></div><label className="mt-4 flex min-h-12 items-center gap-3 border-2 border-ink bg-paper px-3 font-black"><input type="checkbox" checked={form.enabled} onChange={(event) => set("enabled", event.target.checked)} className="h-6 w-6 accent-accent" />Use this rule for new payouts</label></section>
      {message && <p role="status" className={`border-2 p-3 text-sm font-bold xl:col-span-2 ${message.tone === "good" ? "border-good bg-good-soft text-good" : "border-bad bg-bad-soft text-bad"}`}>{message.text}</p>}<button disabled={busy || splitTotal !== 100 || !form.preferredName.trim() || !form.city.trim()} className="brut-btn min-h-12 bg-ink text-paper xl:col-span-2"><Save aria-hidden size={17} />{busy ? "Saving…" : "Save settings"}</button></form>
    <section className="brut-card overflow-hidden"><div className="border-b-2 border-ink bg-paper-2 p-5"><div className="flex items-center gap-3"><Database aria-hidden size={22} /><div><p className="brut-label">Income-source consent</p><h2 className="mt-1 text-xl font-black">Connections and manual sources</h2></div></div></div><div>{dashboard.sources.map((source) => <article key={source.id} className="flex flex-wrap items-center gap-4 border-b border-ink/30 p-5 last:border-b-0"><div className="min-w-48 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{source.name}</h3><span className={`brut-stamp ${source.status === "ACTIVE" ? "bg-good-soft" : source.status === "REVOKED" ? "bg-bad-soft" : "bg-warn-soft"}`}>{source.status}</span><span className="brut-stamp bg-paper-2">{source.prototype ? "Prototype" : "Connected"}</span></div><p className="mt-2 text-xs font-semibold text-ink-soft">{source.connectionMode.toLowerCase().replaceAll("_", " ")} · Last sync {source.lastSyncAt ? new Date(source.lastSyncAt).toLocaleString("en-IN") : "not applicable"}</p></div>{source.status === "ACTIVE" ? <button type="button" disabled={busy} onClick={() => void sourceStatus(source.id, "PAUSED")} className="brut-btn min-h-11 bg-paper"><Pause aria-hidden size={16} />Pause</button> : source.status === "PAUSED" ? <button type="button" disabled={busy} onClick={() => void sourceStatus(source.id, "ACTIVE")} className="brut-btn min-h-11 bg-good-soft"><Play aria-hidden size={16} />Resume</button> : null}<button type="button" disabled={busy || source.status === "REVOKED"} onClick={() => void sourceStatus(source.id, "REVOKED")} className="brut-btn min-h-11 bg-bad-soft text-bad"><Unplug aria-hidden size={16} />Revoke</button></article>)}</div></section>
    <section className="border-2 border-ink bg-ink p-5 text-paper"><p className="brut-label !text-paper-2">Account</p><div className="mt-3 flex flex-wrap items-center justify-between gap-4"><p className="max-w-2xl text-sm font-semibold text-paper-2">Signing out removes the local session from this device. Your saved Convex data remains available after the next Google sign-in.</p><button type="button" onClick={() => signOut({ callbackUrl: "/" })} className="brut-btn min-h-12 bg-paper text-ink"><LogOut aria-hidden size={17} />Sign out</button></div></section>
  </div>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="grid gap-2"><span className="brut-label">{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 border-2 border-ink bg-paper px-3 text-base font-bold outline-none focus:ring-4 focus:ring-accent/30" required /></label>; }
