import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { BudgetDto } from "@superfinz/shared";
import { SPENDING_CATEGORIES, categoryEmoji } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Empty, Field, Label, Loading, Progress, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";

export default function Budgets() {
  const now = new Date(); const client = useQueryClient(); const [show, setShow] = useState(false); const [category, setCategory] = useState<string>("Food"); const [limit, setLimit] = useState("");
  const query = useQuery({ queryKey: ["budgets", now.getMonth(), now.getFullYear()], queryFn: () => apiFetch<{ budgets: BudgetDto[] }>(`/api/budgets?month=${now.getMonth() + 1}&year=${now.getFullYear()}`) });
  const save = useMutation({ mutationFn: () => apiFetch("/api/budgets", { method: "POST", body: JSON.stringify({ category, limit: Number(limit), month: now.getMonth() + 1, year: now.getFullYear() }) }), onSuccess: async () => { setLimit(""); setShow(false); await Promise.all([client.invalidateQueries({ queryKey: ["budgets"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); }, onError: (e) => Alert.alert("Couldn’t save budget", e instanceof Error ? e.message : "Try again") });
  if (query.isLoading) return <Loading label="Loading budgets…" />;
  return <Screen title="Budgets"><Text style={ui.body}>{now.toLocaleDateString("en-IN", { month: "long", year: "numeric" })} category limits</Text><Button title={show ? "Close" : "+ Set category budget"} onPress={() => setShow((v) => !v)} />{show && <Card><Label>Category</Label><View style={styles.chips}>{SPENDING_CATEGORIES.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.active]}><Text style={[styles.chipText, category === item && { color: colors.white }]}>{categoryEmoji(item)} {item}</Text></Pressable>)}</View><Field label="Monthly limit" value={limit} onChangeText={setLimit} keyboardType="numeric" placeholder="₹ 5,000" /><Button title={save.isPending ? "Saving…" : "Save limit"} disabled={save.isPending || !limit} onPress={() => save.mutate()} /></Card>}{!query.data?.budgets.length ? <Empty title="No category limits" body="Add one to get alerts before spending runs away." /> : query.data.budgets.map((budget) => { const pct = budget.limit ? budget.spent / budget.limit * 100 : 0; return <Card key={budget.id}><View style={ui.between}><Text style={ui.h2}>{categoryEmoji(budget.category)} {budget.category}</Text><Text style={[styles.pct, pct > 100 && { color: colors.red }]}>{Math.round(pct)}%</Text></View><Progress value={pct} tone={pct > 100 ? colors.red : pct > 80 ? colors.yellow : colors.green} /><Text style={ui.body}>₹{Math.round(budget.spent).toLocaleString("en-IN")} spent of ₹{Math.round(budget.limit).toLocaleString("en-IN")}</Text></Card>; })}</Screen>;
}
const styles = StyleSheet.create({ chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderWidth: 2, borderColor: colors.ink, padding: 8, backgroundColor: colors.paper }, active: { backgroundColor: colors.ink }, chipText: { fontSize: 11, fontWeight: "800", color: colors.ink }, pct: { color: colors.ink, fontWeight: "900", fontSize: 18 } });
