import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { GoalDto } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Empty, Field, Label, Loading, Progress, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";

export default function Goals() {
  const client = useQueryClient(); const [show, setShow] = useState(false); const [title, setTitle] = useState(""); const [target, setTarget] = useState(""); const [essential, setEssential] = useState(false);
  const query = useQuery({ queryKey: ["goals"], queryFn: () => apiFetch<{ goals: GoalDto[] }>("/api/goals") });
  const invalidate = () => Promise.all([client.invalidateQueries({ queryKey: ["goals"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]);
  const create = useMutation({ mutationFn: () => apiFetch("/api/goals", { method: "POST", body: JSON.stringify({ title, targetAmount: Number(target), isEssential: essential }) }), onSuccess: async () => { setTitle(""); setTarget(""); setShow(false); await invalidate(); }, onError: (e) => Alert.alert("Couldn’t create goal", e instanceof Error ? e.message : "Try again") });
  const update = useMutation({ mutationFn: ({ id, savedAmount, achieved }: { id: string; savedAmount?: number; achieved?: boolean }) => apiFetch("/api/goals", { method: "PATCH", body: JSON.stringify({ id, savedAmount, achieved }) }), onSuccess: invalidate });
  if (query.isLoading) return <Loading label="Loading goals…" />;
  return <Screen title="Goals"><Button title={show ? "Close" : "+ New goal"} onPress={() => setShow((v) => !v)} />{show && <Card><Field label="Goal name" value={title} onChangeText={setTitle} placeholder="Emergency fund" /><Field label="Target amount" value={target} onChangeText={setTarget} keyboardType="numeric" placeholder="₹ 1,00,000" /><Pressable onPress={() => setEssential((v) => !v)} style={[styles.toggle, essential && styles.toggleActive]}><Text style={[styles.toggleText, essential && { color: colors.white }]}>{essential ? "✓ " : ""}ESSENTIAL GOAL</Text></Pressable><Button title={create.isPending ? "Creating…" : "Create goal"} disabled={create.isPending || !title || !target} onPress={() => create.mutate()} /></Card>}{!query.data?.goals.length ? <Empty title="No goals yet" body="Give your savings a destination." /> : query.data.goals.map((goal) => { const pct = goal.targetAmount ? goal.savedAmount / goal.targetAmount * 100 : 0; const step = Math.max(100, Math.round(goal.targetAmount * .05)); return <Card key={goal.id} style={goal.achieved ? { backgroundColor: colors.greenSoft } : undefined}><View style={ui.between}><View style={{ flex: 1 }}><Label>{goal.isEssential ? "Essential" : "Savings goal"}</Label><Text style={ui.h2}>{goal.title}</Text></View><Text style={styles.percent}>{Math.round(pct)}%</Text></View><Progress value={pct} tone={goal.achieved ? colors.green : colors.accent} /><Text style={ui.body}>₹{Math.round(goal.savedAmount).toLocaleString("en-IN")} of ₹{Math.round(goal.targetAmount).toLocaleString("en-IN")}</Text>{!goal.achieved && <View style={styles.actions}><View style={{ flex: 1 }}><Button title={`+ ₹${step.toLocaleString("en-IN")}`} tone="quiet" onPress={() => update.mutate({ id: goal.id, savedAmount: Math.min(goal.targetAmount, goal.savedAmount + step) })} /></View><View style={{ flex: 1 }}><Button title="Mark done" tone="ink" onPress={() => update.mutate({ id: goal.id, achieved: true })} /></View></View>}</Card>; })}</Screen>;
}
const styles = StyleSheet.create({ toggle: { minHeight: 44, borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.paper, alignItems: "center", justifyContent: "center" }, toggleActive: { backgroundColor: colors.ink }, toggleText: { color: colors.ink, fontWeight: "900", fontSize: 11 }, percent: { color: colors.accent, fontWeight: "900", fontSize: 24 }, actions: { flexDirection: "row", gap: 10 } });
