import { useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UserDto } from "@superfinz/shared";
import { financePlanError, summarizeFinancePlan } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Field, Label, Loading, Money, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";
import { useAuth } from "@/providers/auth-provider";

export default function Profile() { const query = useQuery({ queryKey: ["profile"], queryFn: () => apiFetch<{ user: UserDto }>("/api/profile") }); if (!query.data?.user) return <Loading label="Loading profile…" />; return <ProfileForm key={query.data.user.updatedAt} user={query.data.user} />; }

function ProfileForm({ user }: { user: UserDto }) {
  const { signOut } = useAuth(); const client = useQueryClient(); const profile = user.profile; const isProfessional = user.userType === "PROFESSIONAL"; const [income, setIncome] = useState(String(profile?.monthlySalary ?? profile?.monthlyAllowance ?? 0)); const [budget, setBudget] = useState(String(profile?.monthlyBudget ?? 0)); const [savings, setSavings] = useState(String(profile?.savingsGoal ?? 0)); const [institution, setInstitution] = useState(profile?.institution ?? ""); const [company, setCompany] = useState(profile?.company ?? ""); const [industry, setIndustry] = useState(profile?.industry ?? ""); const plan = summarizeFinancePlan({ monthlyIncome: Number(income), monthlyBudget: Number(budget), savingsGoal: Number(savings) }); const planError = financePlanError({ monthlyIncome: Number(income), monthlyBudget: Number(budget), savingsGoal: Number(savings) });
  const save = useMutation({ mutationFn: () => apiFetch("/api/profile", { method: "PATCH", body: JSON.stringify({ ...(isProfessional ? { monthlySalary: Number(income), company, industry } : { monthlyAllowance: Number(income), institution }), monthlyBudget: Number(budget), savingsGoal: Number(savings) }) }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["profile"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); Alert.alert("Saved", "Your plan is up to date."); }, onError: (error) => Alert.alert("Couldn’t save", error instanceof Error ? error.message : "Try again") });
  return <Screen title="Profile"><Card><Label>Account</Label><Text style={ui.h2}>{user.name}</Text><Text style={ui.body}>{user.email}</Text><Text style={ui.small}>{user.userType.replaceAll("_", " ")} · {user.age} years · member since {new Date(user.createdAt).toLocaleDateString("en-IN", { month: "short", year: "numeric" })}</Text></Card><Card><Label>Personal details</Label>{isProfessional ? <><Field label="Company" value={company} onChangeText={setCompany} /><Field label="Industry" value={industry} onChangeText={setIndustry} /></> : <Field label="Institution" value={institution} onChangeText={setInstitution} />}<Field label={isProfessional ? "Monthly salary" : "Monthly allowance"} value={income} onChangeText={setIncome} keyboardType="numeric" /><Field label="Monthly spending budget" value={budget} onChangeText={setBudget} keyboardType="numeric" /><Field label="Monthly savings goal" value={savings} onChangeText={setSavings} keyboardType="numeric" /><View style={styles.plan}><View><Label>Allocated</Label><Money value={plan.allocated} /></View><View><Label>Left</Label><Money value={plan.remaining} /></View></View>{planError && <Text style={styles.error}>{planError}</Text>}<Button title={save.isPending ? "Saving…" : "Save plan"} disabled={save.isPending || !!planError} onPress={() => save.mutate()} /></Card><Card><Label>Session</Label><Text style={ui.body}>Your login tokens are kept in the device’s encrypted secure storage and refresh automatically.</Text><Button title="Sign out" tone="ink" onPress={() => signOut()} /></Card></Screen>;
}
const styles = StyleSheet.create({ plan: { flexDirection: "row", justifyContent: "space-between", gap: 14, backgroundColor: colors.paper, borderWidth: 2, borderColor: colors.ink, padding: 12 }, error: { color: colors.red, fontWeight: "700", fontSize: 12, lineHeight: 18 } });
