import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { StyleSheet, Text, View } from "react-native";
import Slider from "@react-native-community/slider";
import type { UserDto } from "@superfinz/shared";
import { calculateRetirement } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Card, Field, Label, Loading, Money, Progress, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";

export default function Retirement() { const query = useQuery({ queryKey: ["profile"], queryFn: () => apiFetch<{ user: UserDto }>("/api/profile") }); if (!query.data) return <Loading label="Calculating your plan…" />; return <Planner key={query.data.user.updatedAt} user={query.data.user} />; }

function Planner({ user }: { user: UserDto }) {
  const income = user.profile?.monthlySalary ?? user.profile?.monthlyAllowance ?? 0;
  const [currentAge, setCurrentAge] = useState(user.age || 21); const [retirementAge, setRetirementAge] = useState(45);
  const [monthlyInvestment, setMonthlyInvestment] = useState(String(user.profile?.savingsGoal || 3000)); const [monthlyExpenses, setMonthlyExpenses] = useState(String(Math.max(income - (user.profile?.savingsGoal ?? 0), income * .7) || 15000)); const [currentSavings, setCurrentSavings] = useState("0"); const [annualReturn, setAnnualReturn] = useState(12); const [inflation, setInflation] = useState(6);
  const result = calculateRetirement({ currentAge, retirementAge, monthlyInvestment: Number(monthlyInvestment), monthlyExpenses: Number(monthlyExpenses), currentSavings: Number(currentSavings), annualReturn, inflation }); const readiness = result.targetCorpus ? Math.min(100, result.projectedCorpus / result.targetCorpus * 100) : 0;
  return <Screen title="Retirement"><Card style={{ backgroundColor: result.onTrack ? colors.greenSoft : colors.ink }}><Label>{result.onTrack ? "On track" : "Gap to close"}</Label><Text style={[styles.headline, result.onTrack && { color: colors.ink }]}>{result.onTrack ? "Your projection covers the target" : `₹${formatCompact(result.corpusGap)} short`}</Text><Progress value={readiness} tone={result.onTrack ? colors.green : colors.accent} /><Text style={[ui.small, !result.onTrack && { color: colors.paper2 }]}>{Math.round(readiness)}% funded by age {retirementAge}</Text></Card><Card><Label>Your numbers</Label><Range label={`Current age: ${currentAge}`} value={currentAge} minimum={15} maximum={50} onChange={setCurrentAge} /><Range label={`Target retirement age: ${retirementAge}`} value={retirementAge} minimum={Math.max(30, currentAge + 1)} maximum={65} onChange={setRetirementAge} /><Field label="Monthly SIP" value={monthlyInvestment} onChangeText={setMonthlyInvestment} keyboardType="numeric" /><Field label="Monthly expenses" value={monthlyExpenses} onChangeText={setMonthlyExpenses} keyboardType="numeric" /><Field label="Existing savings" value={currentSavings} onChangeText={setCurrentSavings} keyboardType="numeric" /><Range label={`Expected return: ${annualReturn}% CAGR`} value={annualReturn} minimum={6} maximum={18} onChange={setAnnualReturn} /><Range label={`Inflation: ${inflation}%`} value={inflation} minimum={3} maximum={10} onChange={setInflation} /></Card><View style={styles.row}><Card style={{ flex: 1 }}><Label>FIRE target</Label><Money value={result.targetCorpus} compact /><Text style={ui.small}>inflation adjusted</Text></Card><Card style={{ flex: 1 }}><Label>Projected</Label><Money value={result.projectedCorpus} compact /><Text style={ui.small}>at {annualReturn}%</Text></Card></View><Card style={{ backgroundColor: colors.accentSoft }}><Label>Monthly SIP needed</Label><Money value={result.requiredMonthlyInvestment} /><Text style={ui.body}>{result.requiredMonthlyInvestment > Number(monthlyInvestment) ? `Increase by about ₹${Math.round(result.requiredMonthlyInvestment - Number(monthlyInvestment)).toLocaleString("en-IN")} per month.` : "Your current monthly investment meets this illustration."}</Text></Card><Card><Label>Important</Label><Text style={ui.body}>This is an educational projection, not a guarantee or investment recommendation. Returns, inflation, taxes and fees can materially change the outcome.</Text></Card></Screen>;
}
function Range({ label, value, minimum, maximum, onChange }: { label: string; value: number; minimum: number; maximum: number; onChange: (value: number) => void }) { return <View style={{ gap: 3 }}><Label>{label}</Label><Slider value={value} minimumValue={minimum} maximumValue={maximum} step={1} onValueChange={onChange} minimumTrackTintColor={colors.accent} maximumTrackTintColor={colors.paper2} thumbTintColor={colors.ink} /></View>; }
function formatCompact(value: number) { return value >= 10_000_000 ? `${(value / 10_000_000).toFixed(1)}Cr` : value >= 100_000 ? `${(value / 100_000).toFixed(1)}L` : Math.round(value).toLocaleString("en-IN"); }
const styles = StyleSheet.create({ headline: { color: colors.white, fontSize: 26, lineHeight: 31, fontWeight: "900" }, row: { flexDirection: "row", gap: 12 } });
