import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { File, Paths } from "expo-file-system";
import * as Sharing from "expo-sharing";
import type { TransactionDto } from "@superfinz/shared";
import { SPENDING_CATEGORIES, categoryEmoji } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Empty, Field, Label, Loading, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";

export default function Transactions() {
  const client = useQueryClient(); const [showForm, setShowForm] = useState(false); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState<string>("Food");
  const query = useQuery({ queryKey: ["transactions"], queryFn: () => apiFetch<{ transactions: TransactionDto[]; total: number }>("/api/transactions?limit=200") });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ["transactions"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); };
  const create = useMutation({ mutationFn: () => apiFetch<{ transaction: TransactionDto }>("/api/transactions", { method: "POST", body: JSON.stringify({ amount: Number(amount), description, category, date: new Date().toISOString() }) }), onSuccess: async ({ transaction }) => { setAmount(""); setDescription(""); setShowForm(false); await refresh(); try { const check = await apiFetch<{ aiNote: string }>("/api/ai-check", { method: "POST", body: JSON.stringify({ transactionId: transaction.id, amount: transaction.amount, category: transaction.category, description: transaction.description }) }); Alert.alert("Finz says", check.aiNote); } catch { /* transaction is already safely saved */ } }, onError: (cause) => Alert.alert("Couldn’t add spend", cause instanceof Error ? cause.message : "Try again") });
  const remove = useMutation({ mutationFn: (id: string) => apiFetch(`/api/transactions/${id}`, { method: "DELETE" }), onSuccess: refresh, onError: (cause) => Alert.alert("Couldn’t delete", cause instanceof Error ? cause.message : "Try again") });
  const exportCsv = async () => {
    const rows = query.data?.transactions ?? []; const escape = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = ["Date,Description,Category,Amount,Necessary", ...rows.map((tx) => [tx.date.slice(0, 10), tx.description, tx.category, tx.amount, tx.isNecessary ?? ""].map(escape).join(","))].join("\n");
    const file = new File(Paths.cache, `superfinz-transactions-${new Date().toISOString().slice(0, 10)}.csv`); file.create({ overwrite: true }); file.write(csv); await Sharing.shareAsync(file.uri, { mimeType: "text/csv", dialogTitle: "Export transactions" });
  };
  if (query.isLoading) return <Loading label="Loading spends…" />;
  return <Screen title="Spends" action={<Pressable onPress={exportCsv}><Text style={styles.link}>EXPORT</Text></Pressable>}><Button title={showForm ? "Close" : "+ Log a spend"} onPress={() => setShowForm((value) => !value)} />{showForm && <Card><Field label="Amount" value={amount} onChangeText={setAmount} keyboardType="numeric" placeholder="₹ 450" /><Field label="What was it?" value={description} onChangeText={setDescription} placeholder="Lunch with friends" /><Label>Category</Label><View style={styles.chips}>{SPENDING_CATEGORIES.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && { color: colors.white }]}>{categoryEmoji(item)} {item}</Text></Pressable>)}</View><Button title={create.isPending ? "Adding…" : "Add transaction"} disabled={create.isPending || !amount || !description} onPress={() => create.mutate()} /></Card>}{!query.data?.transactions.length ? <Empty title="No spends yet" body="Your first transaction will show up here." /> : query.data.transactions.map((tx) => <Card key={tx.id}><View style={ui.between}><View style={{ flex: 1 }}><Text style={styles.name}>{categoryEmoji(tx.category)} {tx.description}</Text><Text style={ui.small}>{tx.category} · {new Date(tx.date).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</Text></View><Text style={styles.amount}>₹{Math.round(tx.amount).toLocaleString("en-IN")}</Text></View>{tx.aiNote && <Text style={styles.note}>{tx.aiNote}</Text>}<Pressable onPress={() => Alert.alert("Delete spend?", "This also reverses its category budget.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => remove.mutate(tx.id) }])}><Text style={styles.delete}>DELETE</Text></Pressable></Card>)}</Screen>;
}
const styles = StyleSheet.create({ link: { color: colors.accent, fontWeight: "900", fontSize: 11 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderWidth: 2, borderColor: colors.ink, backgroundColor: colors.paper, paddingHorizontal: 9, paddingVertical: 8 }, chipActive: { backgroundColor: colors.ink }, chipText: { color: colors.ink, fontWeight: "800", fontSize: 11 }, name: { color: colors.ink, fontWeight: "900", fontSize: 15 }, amount: { color: colors.ink, fontWeight: "900", fontSize: 17 }, note: { backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.ink, padding: 10, color: colors.inkSoft, lineHeight: 18, fontWeight: "600" }, delete: { color: colors.red, fontWeight: "900", fontSize: 10, textAlign: "right" } });
