import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from "react-native";
import { apiFetch } from "@/lib/api";
import { Button, Field } from "@/components/ui";
import { colors } from "@/constants/theme";

type Message = { role: "user" | "assistant"; content: string };
export default function Chat() { const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Hey! Ask me about your budget, a purchase, or one of your goals." }]); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const send = async () => { if (!message.trim() || sending) return; const text = message.trim(); const history = messages.slice(-12); setMessages((items) => [...items, { role: "user", content: text }]); setMessage(""); setSending(true); try { const result = await apiFetch<{ reply: string }>("/api/chat", { method: "POST", body: JSON.stringify({ message: text, history }) }); setMessages((items) => [...items, { role: "assistant", content: result.reply }]); } catch (e) { Alert.alert("Finz is unavailable", e instanceof Error ? e.message : "Try again"); } finally { setSending(false); } }; return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.page} keyboardVerticalOffset={90}><ScrollView contentContainerStyle={styles.messages}>{messages.map((item, index) => <View key={index} style={[styles.bubble, item.role === "user" ? styles.user : styles.assistant]}><Text style={[styles.text, item.role === "user" && { color: colors.white }]}>{item.content}</Text></View>)}</ScrollView><View style={styles.composer}><View style={{ flex: 1 }}><Field value={message} onChangeText={setMessage} placeholder="Should I buy…?" onSubmitEditing={send} /></View><Button title={sending ? "…" : "Send"} disabled={sending} onPress={send} /></View></KeyboardAvoidingView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, messages: { padding: 16, gap: 12 }, bubble: { maxWidth: "86%", borderWidth: 2, borderColor: colors.ink, padding: 13 }, assistant: { alignSelf: "flex-start", backgroundColor: colors.white }, user: { alignSelf: "flex-end", backgroundColor: colors.ink }, text: { color: colors.ink, fontWeight: "600", lineHeight: 20 }, composer: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12, borderTopWidth: 2, borderColor: colors.ink, backgroundColor: colors.paper } });
