import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import type { IncomeSource, UserType } from "@superfinz/shared";
import { financePlanError, summarizeFinancePlan } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Field, Label, Money, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";
import { useAuth } from "@/providers/auth-provider";

const types: Array<{ value: UserType; label: string }> = [{ value: "SCHOOL_STUDENT", label: "School" }, { value: "COLLEGE_STUDENT", label: "College" }, { value: "PROFESSIONAL", label: "Professional" }];
const sources: Array<{ value: IncomeSource; label: string }> = [{ value: "PARENTS", label: "Parents" }, { value: "SCHOLARSHIP", label: "Scholarship" }, { value: "PART_TIME", label: "Part-time" }, { value: "FREELANCE", label: "Freelance" }, { value: "OTHER", label: "Other" }];
const patterns = [{ value: "FRONT_HEAVY", label: "Front-heavy", body: "More room near month start" }, { value: "BALANCED", label: "Balanced", body: "Even weekly allowance" }, { value: "CONSERVATIVE", label: "Conservative", body: "More room near month end" }] as const;

export default function Onboarding() {
  const { user, reloadUser } = useAuth(); const [userType, setUserType] = useState<UserType>("COLLEGE_STUDENT"); const [age, setAge] = useState(String(user?.age ?? 21)); const [income, setIncome] = useState(""); const [budget, setBudget] = useState(""); const [savings, setSavings] = useState(""); const [institution, setInstitution] = useState(""); const [company, setCompany] = useState(""); const [industry, setIndustry] = useState(""); const [incomeSources, setIncomeSources] = useState<IncomeSource[]>([]); const [spendingPattern, setSpendingPattern] = useState<(typeof patterns)[number]["value"]>("BALANCED"); const [saving, setSaving] = useState(false);
  const isProfessional = userType === "PROFESSIONAL"; const plan = summarizeFinancePlan({ monthlyIncome: Number(income), monthlyBudget: Number(budget), savingsGoal: Number(savings) }); const planError = income && budget ? financePlanError({ monthlyIncome: Number(income), monthlyBudget: Number(budget), savingsGoal: Number(savings) }) : null;
  const toggleSource = (source: IncomeSource) => setIncomeSources((items) => items.includes(source) ? items.filter((item) => item !== source) : [...items, source]);
  const submit = async () => {
    setSaving(true);
    try { await apiFetch("/api/profile/complete", { method: "POST", body: JSON.stringify({ age: Number(age), userType, ...(isProfessional ? { company: company || undefined, industry: industry || undefined, monthlySalary: Number(income) } : { institution: institution || undefined, incomeSources, monthlyAllowance: Number(income) }), monthlyBudget: Number(budget), savingsGoal: Number(savings), spendingPattern, cycleStartDate: 1 }) }); await reloadUser(); }
    catch (cause) { Alert.alert("Check your plan", cause instanceof Error ? cause.message : "Could not save your plan"); } finally { setSaving(false); }
  };
  return <Screen><Text style={ui.h1}>Let’s build your{`\n`}money baseline.</Text><Text style={ui.body}>These details power your weekly allowance, goals, and recommendations. You can edit them later.</Text><Card><Label>I’m a</Label><View style={styles.choices}>{types.map((type) => <Choice key={type.value} selected={userType === type.value} label={type.label} onPress={() => setUserType(type.value)} />)}</View><Field label="Age" value={age} onChangeText={setAge} keyboardType="number-pad" />{isProfessional ? <><Field label="Company" value={company} onChangeText={setCompany} placeholder="Company name" /><Field label="Industry" value={industry} onChangeText={setIndustry} placeholder="Technology, finance…" /></> : <><Field label="Institution" value={institution} onChangeText={setInstitution} placeholder="School or college" /><Label>Income sources</Label><View style={styles.wrap}>{sources.map((source) => <Choice key={source.value} selected={incomeSources.includes(source.value)} label={source.label} onPress={() => toggleSource(source.value)} />)}</View></>}<Field label={isProfessional ? "Monthly salary" : "Monthly allowance"} value={income} onChangeText={setIncome} keyboardType="numeric" placeholder="₹ 40,000" /></Card><Card><Label>My spending pattern</Label>{patterns.map((pattern) => <Pressable key={pattern.value} onPress={() => setSpendingPattern(pattern.value)} style={[styles.pattern, spendingPattern === pattern.value && styles.patternActive]}><View><Text style={[styles.patternTitle, spendingPattern === pattern.value && { color: colors.white }]}>{pattern.label}</Text><Text style={[ui.small, spendingPattern === pattern.value && { color: colors.paper2 }]}>{pattern.body}</Text></View><Text style={[styles.radio, spendingPattern === pattern.value && { color: colors.accent }]}>●</Text></Pressable>)}</Card><Card><Field label="Monthly spending budget" value={budget} onChangeText={setBudget} keyboardType="numeric" placeholder="₹ 25,000" /><Field label="Monthly savings goal" value={savings} onChangeText={setSavings} keyboardType="numeric" placeholder="₹ 8,000" />{income && <View style={styles.plan}><View><Label>Income</Label><Money value={plan.monthlyIncome} /></View><View><Label>Left after plan</Label><Money value={plan.remaining} /></View></View>}{planError && <Text style={styles.error}>{planError}</Text>}</Card><Button title={saving ? "Saving…" : "Create my plan"} disabled={saving || !income || !budget || !!planError} onPress={submit} /></Screen>;
}
function Choice({ selected, label, onPress }: { selected: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.choice, selected && styles.selected]}><Text style={[styles.choiceText, selected && { color: colors.white }]}>{selected ? "✓ " : ""}{label}</Text></Pressable>; }
const styles = StyleSheet.create({ choices: { flexDirection: "row", gap: 8 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { flexGrow: 1, borderWidth: 2, borderColor: colors.ink, minHeight: 44, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", backgroundColor: colors.paper }, selected: { backgroundColor: colors.ink }, choiceText: { fontSize: 11, fontWeight: "900", textTransform: "uppercase", color: colors.ink }, pattern: { borderWidth: 2, borderColor: colors.ink, minHeight: 60, padding: 11, backgroundColor: colors.paper, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, patternActive: { backgroundColor: colors.ink }, patternTitle: { color: colors.ink, fontWeight: "900", textTransform: "uppercase", fontSize: 12 }, radio: { color: colors.paper2, fontSize: 18 }, plan: { flexDirection: "row", justifyContent: "space-between", gap: 15, paddingTop: 5 }, error: { color: colors.red, fontWeight: "700", fontSize: 12, lineHeight: 18 } });
