import { useEffect, useMemo, useState } from "react";
import { Alert, Text, View } from "react-native";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { router } from "expo-router";
import type { DashboardDto } from "@superfinz/shared";
import { apiFetch } from "@/lib/api";
import { Button, Card, Empty, Field, Label, Loading, Money, Screen, ui } from "@/components/ui";
import { colors } from "@/constants/theme";

export default function SmartSplit() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["dashboard"], queryFn: () => apiFetch<{ dashboard: DashboardDto }>("/api/dashboard") }); const [allocations, setAllocations] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false);
  const goals = useMemo(() => [...(query.data?.dashboard.goals.filter((goal) => !goal.achieved) ?? [])].sort((a, b) => Number(b.isEssential) - Number(a.isEssential) || (a.deadline ? new Date(a.deadline).getTime() : Infinity) - (b.deadline ? new Date(b.deadline).getTime() : Infinity)), [query.data]); const available = Math.max(0, query.data?.dashboard.summary.remaining ?? 0);
  useEffect(() => { if (!goals.length || available <= 0) return; let left = available; const next: Record<string, string> = {}; goals.forEach((goal, index) => { let amount = index === 0 ? Math.floor(available * .5) : index === 1 ? Math.floor(available * .3) : Math.floor(left / Math.max(1, goals.length - index)); amount = Math.min(left, amount, Math.max(0, goal.targetAmount - goal.savedAmount)); next[goal.id] = String(amount); left -= amount; }); setAllocations(next); }, [available, goals]);
  if (query.isLoading) return <Loading label="Finding your extra cash…" />;
  const allocated = Object.values(allocations).reduce((sum, value) => sum + (Number(value) || 0), 0);
  const apply = async () => { if (allocated > available) return Alert.alert("Too much allocated", "Keep the total within your remaining budget."); setSaving(true); try { await Promise.all(goals.map((goal) => apiFetch("/api/goals", { method: "PATCH", body: JSON.stringify({ id: goal.id, savedAmount: Math.min(goal.targetAmount, goal.savedAmount + (Number(allocations[goal.id]) || 0)) }) }))); await Promise.all([client.invalidateQueries({ queryKey: ["goals"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); Alert.alert("Split applied", "Your goal balances are updated.", [{ text: "Done", onPress: () => router.back() }]); } catch (e) { Alert.alert("Couldn’t apply split", e instanceof Error ? e.message : "Try again"); } finally { setSaving(false); } };
  return <Screen><Card style={{ backgroundColor: colors.greenSoft }}><Label>Available this month</Label><Money value={available} /><Text style={ui.body}>This is your current budget minus recorded spending. Keep cash needed for upcoming essentials.</Text></Card>{available <= 0 ? <Empty title="Nothing to split yet" body="You’ll see available money here when spending is below budget." /> : !goals.length ? <><Empty title="No active goals" body="Create a goal before splitting extra cash." /><Button title="Go to goals" onPress={() => { router.back(); router.push("/(app)/goals"); }} /></> : <><Card><Label>Suggested allocation</Label><Text style={ui.body}>Essential goals and closer deadlines are prioritized. Adjust any amount before applying.</Text></Card>{goals.map((goal) => <Card key={goal.id}><View style={ui.between}><View><Text style={ui.h2}>{goal.title}</Text><Text style={ui.small}>₹{goal.savedAmount.toLocaleString("en-IN")} / ₹{goal.targetAmount.toLocaleString("en-IN")}</Text></View>{goal.isEssential && <Label>Essential</Label>}</View><Field label="Add to this goal" value={allocations[goal.id] ?? "0"} onChangeText={(value) => setAllocations((items) => ({ ...items, [goal.id]: value }))} keyboardType="numeric" /></Card>)}<Card><View style={ui.between}><Label>Total allocated</Label><Money value={allocated} /></View><Text style={[ui.small, allocated > available && { color: colors.red }]}>₹{Math.max(0, available - allocated).toLocaleString("en-IN")} left unallocated</Text></Card><Button title={saving ? "Applying…" : "Apply smart split"} disabled={saving || allocated <= 0 || allocated > available} onPress={apply} /></>}</Screen>;
}
